### ISSUE TITLE
Investigate: Form widget may be allowing people to omit the required email field

### ISSUE THREAD

**Issue by DingoEatingFuzz** [lytics/pathforajs#153] opened 2016-12-02 20:05 UTC
Internal data shows signs of dropped data. One potential culprit is Pathfora allowing people to submit a form without providing the required email address. Another idea is Pathfora is triggering errant conversion events.

**Comment by sarahyablok** [comment] 2016-12-06 18:33
I have pretty much confirmed that this is a browser issue. In Safari and iOS Safari if I click the submit button with no data entered in the form it will send a `submit` event with no data. 😞 It seems like this is due to the method of validation we use. We should validate with javascript.

Also noticed an interesting bug where if the cancel button is present on a form module it will attempt to submit the data on click rather than closing out the module. Can fix this in pathfora as well, but I also think we should default to exclude the cancel button in Lytics  "Capture Leads" campaigns

**Comment by DingoEatingFuzz** [comment] 2016-12-06 18:43
> I also think we should default to exclude the cancel button in Lytics "Capture Leads" campaigns

Don't we already?

**Comment by sarahyablok** [comment] 2016-12-06 18:47
@DingoEatingFuzz I thought so too, but I noticed that all recent Capture Leads campaigns have the cancel button, and I can't actually remove them with an override! I'm thinking this got changed on accident with some other code change? I can investigate that as well, or have @markhayden do it.

**Closed** 2016-12-08 01:15 UTC
Labels: custeng
